global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'master'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100','cadvisor:8080','localhost:9090','pushgateway:9091']
  
  - job_name: 'node1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.102:9100','192.168.56.102:8080']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
